In [1]:
import numpy as np

In [ ]:
# одномерный массив - вектор
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# сколько элеиентов
np.arange(10).size

10

In [3]:
np.sum(np.arange(10))

45

In [6]:
np.sum(np.arange(10), axis=0)

45

# Оси
Массивы могут быть N-мерными, чаще всего до 4 порядка. Узнать размерность можно через `ndim`

In [7]:
np.arange(10).ndim

1

In [19]:
np.arange(10).dtype

dtype('int32')

Параметр `axis` отвечает за то, по какой оси будет произведена операция. Отсчет осей начинается с 0 и заканчивается $n-1$ для массива с размерностью $n$.
Начнем с 2-мерного массива:

In [ ]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

In [10]:
arr.ndim

2

In [ ]:
# размерность 2 строки, 3 колонки
arr.shape

(2, 3)

Для двумерного массива
- axis=0 - операция по колонкам (по факту группировка по колонкам)
- axis=1 - операция по строкам (группировка по строкам)

In [15]:
np.sum(arr, axis=0)

array([5, 7, 9])

In [17]:
np.sum(arr, axis=1)

array([ 6, 15])

In [24]:
# так же можно задавать тип элементов при создании массивов
np.arange(20, dtype='float').reshape(4, 5)

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]])

In [26]:
array_2 = np.arange(20, dtype='float').reshape(4, 5)

In [29]:
# можно менять форму массива
array_2.shape = 5, 4
array_2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.]])

In [ ]:
3-мерный массив:
- axis=0 - операция в глубину
- axis=1 - 

In [22]:
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])