In [1]:
import numpy as np

**Транспонирование**

In [2]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

**Произведение матриц**

In [3]:
a = np.array([[1, 0],
              [0, 1]])
b = np.array([[4, 1],
              [2, 2]])
np.matmul(a, b)

array([[4, 1],
       [2, 2]])

In [4]:
np.dot(a, b)

array([[4, 1],
       [2, 2]])

**Произведение Адамара**

In [5]:
a = np.array([[1, 0],
              [0, 1]])
b = np.array([[4, 1],
              [2, 2]])
a * b

array([[4, 0],
       [0, 2]])

**Определитель матрицы**

In [6]:
a = np.array([[-1, 1, 1, 0, 1] 
             ,[0, 1, -2, 1, 2]
             ,[0, 0, -1, 3, 3]
             ,[0, 0, 0, 1, 0]
             ,[0, 0, 0, 3, -1]])
np.linalg.det(a)

-1.0

**Обратная матрица и возведение в степень**

In [7]:
a = np.array([[1, 0, 2] 
            ,[2, -1, 1] 
             ,[1, 3, -1]])
np.linalg.matrix_power(a, -1)

array([[-0.16666667,  0.5       ,  0.16666667],
       [ 0.25      , -0.25      ,  0.25      ],
       [ 0.58333333, -0.25      , -0.08333333]])

**Уравнения**

$left$ * $X$ = $right$

In [8]:
# левая часть системы
left = np.array([[-1, 2],
             [2, -3]])
# правая часть
right = np.array([[-2, 3],
             [1, -4]])
np.linalg.solve(left, right)

array([[-4.,  1.],
       [-3.,  2.]])